# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from openapi_client.models.business_business_id_transactions_post_request_params_inner import BusinessBusinessIdTransactionsPostRequestParamsInner
from typing import Optional, Set
from typing_extensions import Self

class BusinessBusinessIdTransactionsPostRequest(BaseModel):
    """
    BusinessBusinessIdTransactionsPostRequest
    """ # noqa: E501
    chain: Union[StrictFloat, StrictInt] = Field(description="Id of a chain")
    contract_address: StrictStr = Field(description="string address of contract", alias="contractAddress")
    escrow_wallet_id: StrictStr = Field(alias="escrowWalletId")
    name: StrictStr
    description: StrictStr
    function_name: StrictStr = Field(alias="functionName")
    params: List[BusinessBusinessIdTransactionsPostRequestParamsInner]
    __properties: ClassVar[List[str]] = ["chain", "contractAddress", "escrowWalletId", "name", "description", "functionName", "params"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BusinessBusinessIdTransactionsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in params (list)
        _items = []
        if self.params:
            for _item_params in self.params:
                if _item_params:
                    _items.append(_item_params.to_dict())
            _dict['params'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BusinessBusinessIdTransactionsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chain": obj.get("chain"),
            "contractAddress": obj.get("contractAddress"),
            "escrowWalletId": obj.get("escrowWalletId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "functionName": obj.get("functionName"),
            "params": [BusinessBusinessIdTransactionsPostRequestParamsInner.from_dict(_item) for _item in obj["params"]] if obj.get("params") is not None else None
        })
        return _obj


