# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EChain(int, Enum):
    """
    The ChainId of a supported chain on 1Shot API
    """

    """
    allowed enum values
    """
    NUMBER_1 = 1
    NUMBER_11155111 = 11155111
    NUMBER_42 = 42
    NUMBER_137 = 137
    NUMBER_43114 = 43114
    NUMBER_43113 = 43113
    NUMBER_80002 = 80002
    NUMBER_100 = 100
    NUMBER_56 = 56
    NUMBER_1284 = 1284
    NUMBER_42161 = 42161
    NUMBER_10 = 10
    NUMBER_592 = 592
    NUMBER_81 = 81
    NUMBER_97 = 97
    NUMBER_101 = 101
    NUMBER_324 = 324
    NUMBER_8453 = 8453
    NUMBER_84532 = 84532
    NUMBER_88888 = 88888
    NUMBER_11297108109 = 11297108109
    NUMBER_42220 = 42220

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EChain from a JSON string"""
        return cls(json.loads(json_str))


