# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ESolidityAbiParameterType(str, Enum):
    """
    ESolidityAbiParameterType
    """

    """
    allowed enum values
    """
    ADDRESS = 'address'
    BOOL = 'bool'
    BYTES = 'bytes'
    INT = 'int'
    STRING = 'string'
    UINT = 'uint'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ESolidityAbiParameterType from a JSON string"""
        return cls(json.loads(json_str))


