# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.e_solidity_abi_parameter_type import ESolidityAbiParameterType

class TestESolidityAbiParameterType(unittest.TestCase):
    """ESolidityAbiParameterType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testESolidityAbiParameterType(self):
        """Test ESolidityAbiParameterType"""
        # inst = ESolidityAbiParameterType()

if __name__ == '__main__':
    unittest.main()
