# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.business_business_id_transactions_post_request import BusinessBusinessIdTransactionsPostRequest

class TestBusinessBusinessIdTransactionsPostRequest(unittest.TestCase):
    """BusinessBusinessIdTransactionsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BusinessBusinessIdTransactionsPostRequest:
        """Test BusinessBusinessIdTransactionsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BusinessBusinessIdTransactionsPostRequest`
        """
        model = BusinessBusinessIdTransactionsPostRequest()
        if include_optional:
            return BusinessBusinessIdTransactionsPostRequest(
                chain = 1337,
                contract_address = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
                escrow_wallet_id = '8a6e0804-2bd0-4672-b79d-d97027f90720',
                name = 'Mint Token',
                description = 'This calls the mint() method on our ERC20 contract',
                function_name = 'mint',
                params = [
                    openapi_client.models._business__business_id__transactions_post_request_params_inner._business__businessId__transactions_post_request_params_inner(
                        name = 'amount', 
                        type = 'address', 
                        index = 0, 
                        value = '', )
                    ]
            )
        else:
            return BusinessBusinessIdTransactionsPostRequest(
                chain = 1337,
                contract_address = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
                escrow_wallet_id = '8a6e0804-2bd0-4672-b79d-d97027f90720',
                name = 'Mint Token',
                description = 'This calls the mint() method on our ERC20 contract',
                function_name = 'mint',
                params = [
                    openapi_client.models._business__business_id__transactions_post_request_params_inner._business__businessId__transactions_post_request_params_inner(
                        name = 'amount', 
                        type = 'address', 
                        index = 0, 
                        value = '', )
                    ],
        )
        """

    def testBusinessBusinessIdTransactionsPostRequest(self):
        """Test BusinessBusinessIdTransactionsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
