# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.business_business_id_wallets_get200_response import BusinessBusinessIdWalletsGet200Response

class TestBusinessBusinessIdWalletsGet200Response(unittest.TestCase):
    """BusinessBusinessIdWalletsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BusinessBusinessIdWalletsGet200Response:
        """Test BusinessBusinessIdWalletsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BusinessBusinessIdWalletsGet200Response`
        """
        model = BusinessBusinessIdWalletsGet200Response()
        if include_optional:
            return BusinessBusinessIdWalletsGet200Response(
                page = 1,
                page_size = 25,
                total_results = 1,
                response = [
                    null
                    ]
            )
        else:
            return BusinessBusinessIdWalletsGet200Response(
        )
        """

    def testBusinessBusinessIdWalletsGet200Response(self):
        """Test BusinessBusinessIdWalletsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
