# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.escrow_wallet import EscrowWallet

class TestEscrowWallet(unittest.TestCase):
    """EscrowWallet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EscrowWallet:
        """Test EscrowWallet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EscrowWallet`
        """
        model = EscrowWallet()
        if include_optional:
            return EscrowWallet(
                updated = 1659485172,
                created = 1659485172,
                id = '4b4bab2d-673d-4b91-8e09-f1402962cd3e',
                account_address = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
                business_id = '',
                user_id = '',
                chain_id = 1337,
                name = '',
                description = '',
                is_admin = True,
                account_balance_details = None
            )
        else:
            return EscrowWallet(
        )
        """

    def testEscrowWallet(self):
        """Test EscrowWallet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
