# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transactions_transaction_id_test_post_request import TransactionsTransactionIdTestPostRequest

class TestTransactionsTransactionIdTestPostRequest(unittest.TestCase):
    """TransactionsTransactionIdTestPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsTransactionIdTestPostRequest:
        """Test TransactionsTransactionIdTestPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsTransactionIdTestPostRequest`
        """
        model = TransactionsTransactionIdTestPostRequest()
        if include_optional:
            return TransactionsTransactionIdTestPostRequest(
                params = {"recipientAddress":"0x3e6a2f0CBA03d293B54c9fCF354948903007a798","amount":"463"}
            )
        else:
            return TransactionsTransactionIdTestPostRequest(
        )
        """

    def testTransactionsTransactionIdTestPostRequest(self):
        """Test TransactionsTransactionIdTestPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
