# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction import Transaction

class TestTransaction(unittest.TestCase):
    """Transaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Transaction:
        """Test Transaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Transaction`
        """
        model = Transaction()
        if include_optional:
            return Transaction(
                deleted = False,
                updated = 1659485172,
                created = 1659485172,
                id = 'f4e3d951-85ad-42fa-8e21-75545145c7cb',
                business_id = '100d2e83-dddd-480d-88ad-74a71c214912',
                chain = 1337,
                contract_address = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
                escrow_wallet_id = '100d2e83-dddd-480d-88ad-74a71c214912',
                name = 'Got good',
                description = 'Transaction for getting good',
                function_name = 'mint',
                params = [
                    openapi_client.models.solidity_struct_param.SolidityStructParam(
                        id = '100d2e83-dddd-480d-88ad-74a71c214912', 
                        struct_id = '100d2e83-dddd-480d-88ad-74a71c214912', 
                        name = '', 
                        type = 'address', 
                        type_struct_id = '100d2e83-dddd-480d-88ad-74a71c214912', 
                        type_size = 56, 
                        type_size2 = 56, 
                        is_array = True, 
                        array_size = 56, 
                        index = 56, 
                        value = '', 
                        type_struct = null, )
                    ],
                callback_url = '',
                public_key = ''
            )
        else:
            return Transaction(
        )
        """

    def testTransaction(self):
        """Test Transaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
