# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transactions_transaction_id_put_request import TransactionsTransactionIdPutRequest

class TestTransactionsTransactionIdPutRequest(unittest.TestCase):
    """TransactionsTransactionIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsTransactionIdPutRequest:
        """Test TransactionsTransactionIdPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsTransactionIdPutRequest`
        """
        model = TransactionsTransactionIdPutRequest()
        if include_optional:
            return TransactionsTransactionIdPutRequest(
                chain = 1,
                contract_address = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
                escrow_wallet_id = '0388046f-7b31-8477-793f-2b96ed6eb91e',
                name = '',
                description = '',
                function_name = '',
                payable = True,
                native_transaction = True,
                callback_url = 'https://my-server.com/1shotwebhook'
            )
        else:
            return TransactionsTransactionIdPutRequest(
        )
        """

    def testTransactionsTransactionIdPutRequest(self):
        """Test TransactionsTransactionIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
