# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.escrow_wallets_api import EscrowWalletsApi


class TestEscrowWalletsApi(unittest.TestCase):
    """EscrowWalletsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EscrowWalletsApi()

    def tearDown(self) -> None:
        pass

    def test_business_business_id_wallets_get(self) -> None:
        """Test case for business_business_id_wallets_get

        """
        pass

    def test_business_business_id_wallets_post(self) -> None:
        """Test case for business_business_id_wallets_post

        """
        pass

    def test_wallets_escrow_wallet_id_delete(self) -> None:
        """Test case for wallets_escrow_wallet_id_delete

        """
        pass

    def test_wallets_escrow_wallet_id_get(self) -> None:
        """Test case for wallets_escrow_wallet_id_get

        """
        pass

    def test_wallets_escrow_wallet_id_put(self) -> None:
        """Test case for wallets_escrow_wallet_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
