# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallets_escrow_wallet_id_delete200_response import WalletsEscrowWalletIdDelete200Response

class TestWalletsEscrowWalletIdDelete200Response(unittest.TestCase):
    """WalletsEscrowWalletIdDelete200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletsEscrowWalletIdDelete200Response:
        """Test WalletsEscrowWalletIdDelete200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletsEscrowWalletIdDelete200Response`
        """
        model = WalletsEscrowWalletIdDelete200Response()
        if include_optional:
            return WalletsEscrowWalletIdDelete200Response(
                success = True
            )
        else:
            return WalletsEscrowWalletIdDelete200Response(
        )
        """

    def testWalletsEscrowWalletIdDelete200Response(self):
        """Test WalletsEscrowWalletIdDelete200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
