# coding: utf-8

"""
    M2M Gateway API

    The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework

    The version of the OpenAPI document: 0.1
    Contact: support@uxly.software
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.update_api import UpdateApi


class TestUpdateApi(unittest.TestCase):
    """UpdateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpdateApi()

    def tearDown(self) -> None:
        pass

    def test_transactions_transaction_id_put(self) -> None:
        """Test case for transactions_transaction_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
