/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionExecution } from './transactionExecution';

export class BusinessBusinessIdTransactionsExecutionsGet200Response {
    /**
    * Which page to return. This is 1 indexed, and default to the first page, 1
    */
    'page'?: number;
    /**
    * The size of the page to return. Defaults to 25
    */
    'pageSize'?: number;
    /**
    * The total number of results returned by a paged response
    */
    'totalResults'?: number;
    'response'?: Array<TransactionExecution>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "totalResults",
            "baseName": "totalResults",
            "type": "number"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "Array<TransactionExecution>"
        }    ];

    static getAttributeTypeMap() {
        return BusinessBusinessIdTransactionsExecutionsGet200Response.attributeTypeMap;
    }
}

