/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ESolidityAbiParameterType } from './eSolidityAbiParameterType';

export class BusinessBusinessIdTransactionsPostRequestParamsInner {
    'name': string;
    'type': ESolidityAbiParameterType;
    /**
    * This is the relative index in the contract function. It should start at 0, and must not skip any numbers.
    */
    'index': number;
    /**
    * This is an optional value. This
    */
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ESolidityAbiParameterType"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BusinessBusinessIdTransactionsPostRequestParamsInner.attributeTypeMap;
    }
}

export namespace BusinessBusinessIdTransactionsPostRequestParamsInner {
}
