/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The ChainId of a supported chain on 1Shot API
*/
export enum EChain {
    NUMBER_1 = <any> 1,
    NUMBER_11155111 = <any> 11155111,
    NUMBER_42 = <any> 42,
    NUMBER_137 = <any> 137,
    NUMBER_43114 = <any> 43114,
    NUMBER_43113 = <any> 43113,
    NUMBER_80002 = <any> 80002,
    NUMBER_100 = <any> 100,
    NUMBER_56 = <any> 56,
    NUMBER_1284 = <any> 1284,
    NUMBER_42161 = <any> 42161,
    NUMBER_10 = <any> 10,
    NUMBER_592 = <any> 592,
    NUMBER_81 = <any> 81,
    NUMBER_97 = <any> 97,
    NUMBER_101 = <any> 101,
    NUMBER_324 = <any> 324,
    NUMBER_8453 = <any> 8453,
    NUMBER_84532 = <any> 84532,
    NUMBER_88888 = <any> 88888,
    NUMBER_11297108109 = <any> 11297108109,
    NUMBER_42220 = <any> 42220
}
