/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EntityBookKeepingWithoutDeleted {
    'updated'?: number;
    'created'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return EntityBookKeepingWithoutDeleted.attributeTypeMap;
    }
}

