/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EscrowWalletAllOfAccountBalanceDetails } from './escrowWalletAllOfAccountBalanceDetails';

/**
* Escrow wallet stored by chain service
*/
export class EscrowWallet {
    'updated'?: number;
    'created'?: number;
    /**
    * internal ID of the escrowWallet object
    */
    'id'?: string;
    /**
    * string address of a wallet insight platform holds keys for
    */
    'accountAddress'?: string;
    /**
    * The business ID that owns this wallet. Admin escrow wallets will not have this value. An escrow wallet will have either a user ID or a business ID.
    */
    'businessId'?: string;
    /**
    * The User ID of the person that owns this wallet. Admin escrow wallets will not have this value. An escrow wallet will have either a user ID or a business ID.
    */
    'userId'?: string;
    /**
    * Id of a chain
    */
    'chainId'?: number;
    /**
    * The name of the escrow wallet.
    */
    'name'?: string;
    /**
    * Optional description of the escrow wallet, can be used to describe it\'s purpose.
    */
    'description'?: string;
    /**
    * Whether or not the escrow wallet is an admin escrow wallet, used for internal purposes.
    */
    'isAdmin'?: boolean;
    'accountBalanceDetails'?: EscrowWalletAllOfAccountBalanceDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "accountAddress",
            "baseName": "accountAddress",
            "type": "string"
        },
        {
            "name": "businessId",
            "baseName": "businessId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "isAdmin",
            "baseName": "isAdmin",
            "type": "boolean"
        },
        {
            "name": "accountBalanceDetails",
            "baseName": "accountBalanceDetails",
            "type": "EscrowWalletAllOfAccountBalanceDetails"
        }    ];

    static getAttributeTypeMap() {
        return EscrowWallet.attributeTypeMap;
    }
}

