/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The current status of the webhook
*/
export enum EWebhookStatus {
    Unsent = <any> 'Unsent',
    Success = <any> 'Success',
    Retrying = <any> 'Retrying',
    Failed = <any> 'Failed'
}
