/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetAccessToken200Response {
    /**
    * The OAuth2 access token
    */
    'accessToken'?: string;
    /**
    * Token type (always `Bearer`)
    */
    'tokenType'?: GetAccessToken200Response.TokenTypeEnum;
    /**
    * Expiration time in seconds (usually 3600)
    */
    'expiresIn'?: number;
    /**
    * Granted scopes
    */
    'scope'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "tokenType",
            "baseName": "token_type",
            "type": "GetAccessToken200Response.TokenTypeEnum"
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetAccessToken200Response.attributeTypeMap;
    }
}

export namespace GetAccessToken200Response {
    export enum TokenTypeEnum {
        Bearer = <any> 'Bearer'
    }
}
