/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SolidityStructParam } from './solidityStructParam';

export class SolidityStructParamTypeStruct {
    /**
    * Internal ID of the struct.
    */
    'id'?: string;
    /**
    * Internal ID of the business that owns this struct
    */
    'businessId'?: string;
    /**
    * The name of the struct. Structs are used to define the parameters of a transaction, but these structs don\'t have names.
    */
    'name'?: string;
    'params'?: Array<SolidityStructParam>;
    'deleted'?: boolean;
    'updated'?: number;
    'created'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "businessId",
            "baseName": "businessId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "Array<SolidityStructParam>"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SolidityStructParamTypeStruct.attributeTypeMap;
    }
}

