/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ESolidityAbiParameterType } from './eSolidityAbiParameterType';
import { SolidityStructParamTypeStruct } from './solidityStructParamTypeStruct';

/**
* A single defined parameter for a transaction. This is
*/
export class SolidityStructParam {
    /**
    * Internal ID of the parameter.
    */
    'id'?: string;
    /**
    * Internal ID struct that owns this parameter.
    */
    'structId'?: string;
    /**
    * A name to assign to the parameter. You will pass values to the parameter using this name. For clarity, this should be the name of the parameter on the underlying contract method, but you can set it as whatever you want.
    */
    'name'?: string;
    'type'?: ESolidityAbiParameterType;
    /**
    * The ID of the sub-struct if the type is \"struct\"
    */
    'typeStructId'?: string;
    /**
    * The size of the type for int, uint and bytes. Also used for fixed and ufixed; it is the first size of the type. This must follow the rules for the type; valid values for bytes are 1 to 32, for others is 256 % 8.
    */
    'typeSize'?: number;
    /**
    * The second size for the type. Only used for fixed and ufixed types.
    */
    'typeSize2'?: number;
    /**
    * Set to true if the parameter takes an array of the type.
    */
    'isArray'?: boolean;
    /**
    * If the type array takes a fixed number of elements (IE, 5), this will be set.
    */
    'arraySize'?: number;
    /**
    * The index of the parameter in the contract method. This starts at 0 and must not skip numbers
    */
    'index'?: number;
    /**
    * The static value of the parameter, stored in the transaction itself. All parameters have to have a value at execution, but it can be a mix of static and dynamic parameters
    */
    'value'?: string;
    'typeStruct'?: SolidityStructParamTypeStruct;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "structId",
            "baseName": "structId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ESolidityAbiParameterType"
        },
        {
            "name": "typeStructId",
            "baseName": "typeStructId",
            "type": "string"
        },
        {
            "name": "typeSize",
            "baseName": "typeSize",
            "type": "number"
        },
        {
            "name": "typeSize2",
            "baseName": "typeSize2",
            "type": "number"
        },
        {
            "name": "isArray",
            "baseName": "isArray",
            "type": "boolean"
        },
        {
            "name": "arraySize",
            "baseName": "arraySize",
            "type": "number"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "typeStruct",
            "baseName": "typeStruct",
            "type": "SolidityStructParamTypeStruct"
        }    ];

    static getAttributeTypeMap() {
        return SolidityStructParam.attributeTypeMap;
    }
}

export namespace SolidityStructParam {
}
