/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* You need to provide a value for every parameter in the transaction via the name of the parameter
*/
export class TransactionsTransactionIdTestPostRequest {
    'params'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "params",
            "baseName": "params",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return TransactionsTransactionIdTestPostRequest.attributeTypeMap;
    }
}

