/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ETransactionExecutionStatus } from './eTransactionExecutionStatus';

/**
* A single execution of a transaction- ie, a function call
*/
export class TransactionExecution {
    'deleted'?: boolean;
    'updated'?: number;
    'created'?: number;
    /**
    * internal ID of the transaction execution
    */
    'id'?: string;
    /**
    * internal ID of the transaction
    */
    'transactionId'?: string;
    /**
    * ID of the API Credential used to execute the transaction. Note, this is not the API Key itself. This will be null if a user initiated the execution and not an API Credential
    */
    'apiCredentialId'?: string | null;
    /**
    * The User ID that executed the transaction. This will be null if an API key was used instead of a user token.
    */
    'userId'?: string | null;
    'status'?: ETransactionExecutionStatus;
    /**
    * The ID of the actual chain transaction in the internal chain service.
    */
    'chainTransactionId'?: string;
    'completedTimestamp'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        },
        {
            "name": "apiCredentialId",
            "baseName": "apiCredentialId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ETransactionExecutionStatus"
        },
        {
            "name": "chainTransactionId",
            "baseName": "chainTransactionId",
            "type": "string"
        },
        {
            "name": "completedTimestamp",
            "baseName": "completedTimestamp",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TransactionExecution.attributeTypeMap;
    }
}

export namespace TransactionExecution {
}
