/**
 * M2M Gateway API
 * The M2M Gateway API is for communication by 3rd party servers for automated tasks in the Framework
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@uxly.software
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TransactionsTransactionIdRestorePutRequest {
    'rewardIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rewardIds",
            "baseName": "rewardIds",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return TransactionsTransactionIdRestorePutRequest.attributeTypeMap;
    }
}

